/**
 * The six word pools.
 *
 * Curated by hand, then exported here as plain data — no loader, no database,
 * no network. Each pool is deduplicated: exact repeats inside one pool are a
 * data error (they skew the draw without adding a name), so they are removed
 * at source rather than papered over at runtime.
 *
 * Words appearing in TWO DIFFERENT pools are left alone: a word can honestly
 * be both a descriptor and an action, and the two generators treat that
 * differently. See `mergePools` in ./pools.ts and the entropy notes.
 */

/** Adjectives with a bit of attitude — the descriptive slot. 774 words. */
export const ninjactives: readonly string[] = [
  'able', 'absent', 'actual', 'acute', 'added', 'alert', 'alive', 'alone',
  'amazed', 'angry', 'annual', 'anxious', 'arctic', 'armed', 'ashamed', 'asleep',
  'atomic', 'awake', 'aware', 'awful', 'awkward', 'back', 'bad', 'bare',
  'basic', 'better', 'big', 'bitter', 'blank', 'blind', 'blonde', 'bloody',
  'bold', 'bored', 'boring', 'brainy', 'brave', 'brief', 'bright', 'broad',
  'broken', 'bumpy', 'busy', 'calm', 'careful', 'casual', 'causal', 'certain',
  'cheap', 'chief', 'chilly', 'chosen', 'civic', 'civil', 'clean', 'clear',
  'clever', 'close', 'closed', 'cloudy', 'clumsy', 'coastal', 'coherent', 'cold',
  'common', 'compact', 'complex', 'concern', 'content', 'correct', 'costly', 'crazy',
  'crude', 'cruel', 'cuddly', 'curious', 'curly', 'current', 'curved', 'cute',
  'daily', 'damp', 'dark', 'dead', 'dear', 'decent', 'deep', 'defiant',
  'devoted', 'digital', 'direct', 'dirty', 'dizzy', 'double', 'drab', 'drunk',
  'dry', 'dual', 'due', 'dull', 'dusty', 'dutch', 'dying', 'eager',
  'early', 'easy', 'eerie', 'empty', 'equal', 'ethical', 'ethnic', 'evil',
  'exact', 'exotic', 'expert', 'extra', 'fair', 'famous', 'fancy', 'fast',
  'fat', 'fatal', 'fellow', 'female', 'few', 'fierce', 'filthy', 'final',
  'fine', 'firm', 'fit', 'fixed', 'flaky', 'flat', 'fluffy', 'flying',
  'fond', 'foolish', 'formal', 'fragile', 'frail', 'free', 'fresh', 'frozen',
  'full', 'fun', 'funny', 'fuzzy', 'gay', 'giant', 'given', 'glad',
  'global', 'golden', 'good', 'gothic', 'grand', 'great', 'grim', 'gross',
  'grubby', 'grumpy', 'guilty', 'happy', 'hard', 'harsh', 'head', 'heavy',
  'helpful', 'hidden', 'high', 'holy', 'homely', 'honest', 'hot', 'huge',
  'human', 'hungry', 'hurt', 'icy', 'ideal', 'ill', 'immune', 'import',
  'inner', 'innocent', 'intense', 'itchy', 'jealous', 'jolly', 'juicy', 'junior',
  'just', 'keen', 'key', 'kind', 'known', 'large', 'late', 'lazy',
  'legal', 'lesser', 'liable', 'light', 'likely', 'linear', 'liquid', 'little',
  'live', 'lively', 'living', 'local', 'lonely', 'long', 'loose', 'lost',
  'loud', 'lovely', 'low', 'loyal', 'lucky', 'mad', 'magic', 'main',
  'major', 'male', 'marked', 'mass', 'mean', 'meek', 'mere', 'merry',
  'mighty', 'mild', 'minor', 'misty', 'mixed', 'mobile', 'modern', 'modest',
  'moist', 'moral', 'muddy', 'mushy', 'musical', 'mute', 'mutual', 'naked',
  'narrow', 'nasty', 'native', 'naval', 'near', 'neat', 'nervous', 'new',
  'nice', 'noble', 'noisy', 'normal', 'nosy', 'noted', 'novel', 'nuclear',
  'odd', 'official', 'ok', 'okay', 'old', 'only', 'open', 'oral',
  'organic', 'other', 'outer', 'pale', 'past', 'picky', 'patient', 'period',
  'petite', 'plain', 'plastic', 'pleased', 'polite', 'poor', 'potent', 'precise',
  'pretty', 'prime', 'prior', 'proud', 'pure', 'quick', 'quiet', 'rainy',
  'random', 'rapid', 'rare', 'raw', 'ready', 'real', 'recent', 'rich',
  'rigid', 'ripe', 'rising', 'rocky', 'rotten', 'rough', 'royal', 'rubber',
  'rude', 'ruling', 'rural', 'sacred', 'sad', 'safe', 'salty', 'scared',
  'scary', 'secret', 'secure', 'select', 'selfish', 'senior', 'serious', 'severe',
  'sexual', 'shady', 'shaky', 'sharp', 'sheer', 'shiny', 'short', 'shy',
  'sick', 'silent', 'silky', 'silly', 'simple', 'single', 'skinny', 'sleepy',
  'slight', 'slim', 'slimy', 'slow', 'small', 'smart', 'smooth', 'social',
  'soft', 'solar', 'sole', 'solid', 'sore', 'sorry', 'sound', 'sour',
  'spare', 'spatial', 'special', 'spicy', 'sporty', 'square', 'stable', 'stale',
  'static', 'steady', 'steep', 'sticky', 'stiff', 'still', 'stingy', 'strange',
  'strict', 'strong', 'stuck', 'stupid', 'subtle', 'sudden', 'sunny', 'super',
  'sure', 'sweet', 'swift', 'tall', 'tame', 'tart', 'tasty', 'tender',
  'tense', 'testy', 'thick', 'thin', 'tight', 'tiny', 'tired', 'top',
  'total', 'tough', 'toxic', 'tragic', 'tricky', 'trivial', 'true', 'turbid',
  'typical', 'ugly', 'unable', 'unaware', 'uneven', 'unfair', 'unhappy', 'unique',
  'united', 'unknown', 'unsure', 'untamed', 'unusual', 'urban', 'urgent', 'used',
  'useful', 'useless', 'usual', 'vague', 'valid', 'varied', 'vast', 'verbal',
  'vicious', 'violent', 'visible', 'visual', 'vital', 'vivid', 'vocal', 'warm',
  'weak', 'wealthy', 'weary', 'wee', 'weekly', 'weird', 'welcome', 'well',
  'wet', 'white', 'wicked', 'wide', 'wild', 'willing', 'wily', 'wise',
  'wispy', 'witty', 'wooden', 'working', 'worried', 'worthy', 'written', 'wrong',
  'young', 'yucky', 'yummy', 'zany', 'zealous', 'zesty', 'zippy', 'chido',
  'ninja', 'samurai', 'ronin', 'judoka', 'kendoka', 'aikido', 'karate', 'kungfu',
  'sanda', 'muay', 'capoeira', 'grappler', 'boxer', 'wrestler', 'yudoka', 'sumo',
  'archer', 'spearman', 'slinger', 'fencer', 'monk', 'shinobi', 'shaolin', 'brawler',
  'fighter', 'pankration', 'gladiator', 'hoplite', 'viking', 'legion', 'centurion', 'spartan',
  'mamluk', 'janissary', 'czar', 'nomad', 'raider', 'berserker', 'hussar', 'cossack',
  'warlord', 'soldier', 'guard', 'trooper', 'paladin', 'squire', 'warden', 'reaver',
  'slayer', 'hunter', 'rogue', 'thief', 'assassin', 'barbarian', 'crusader', 'herald',
  'sentry', 'champ', 'hero', 'homer', 'berserk', 'tamer', 'guardian', 'jedi',
  'sith', 'mage', 'wizard', 'sorcer', 'ranger', 'psion', 'druid', 'monado',
  'shinra', 'samson', 'gaiden', 'cypher', 'rider', 'sentinel', 'seer', 'adept',
  'shogun', 'sensei', 'master', 'inquisitor', 'warpriest', 'templar', 'witchhunter', 'huntress',
  'saboteur', 'shadow', 'assail', 'avenger', 'marshal', 'pawn', 'rook', 'knight',
  'bishop', 'queen', 'king', 'castle', 'rookie', 'ruler', 'monarch', 'bart',
  'move', 'push', 'slide', 'hop', 'jump', 'swap', 'trade', 'block',
  'check', 'mate', 'pin', 'fork', 'trap', 'press', 'strike', 'charge',
  'cutoff', 'promotion', 'advance', 'attack', 'defend', 'threat', 'counter', 'bait',
  'blitz', 'draw', 'resign', 'gambit', 'opening', 'endgame', 'zugzwang', 'stalemate',
  'tempo', 'center', 'file', 'rank', 'edge', 'corner', 'decoy', 'shield',
  'pivot', 'flank', 'anchor', 'bridge', 'march', 'sneak', 'chain', 'storm',
  'probe', 'caro', 'nimzo', 'bogo', 'larsen', 'benko', 'kingin', 'queenp',
  'fianchetto', 'alekh', 'capab', 'tarras', 'fischr', 'spassk', 'kaspar', 'botvin',
  'morphy', 'rubin', 'steini', 'tal', 'petro', 'reti', 'benoni', 'pirc',
  'bullet', 'classical', 'otb', 'gm', 'im', 'fm', 'cm', 'elo',
  'grind', 'tilt', 'flag', 'prep', 'theory', 'line', 'mouse', 'click',
  'speed', 'think', 'sneaky', 'sacky', 'grindy', 'stormy', 'crisp', 'archon',
  'astral', 'mystic', 'aether', 'tactix', 'rock', 'pop', 'punk', 'metal',
  'blues', 'jazz', 'folk', 'soul', 'funk', 'disco', 'reggae', 'gospel',
  'country', 'indie', 'techno', 'house', 'trance', 'dub', 'garage', 'grunge',
  'emo', 'ska', 'rap', 'hiphop', 'rnb', 'lofi', 'chill', 'edm',
  'synth', 'ambient', 'glitch', 'acid', 'gabber', 'cyber', 'wave', 'dubstep',
  'samba', 'bossa', 'cumbia', 'tango', 'fado', 'zouk', 'soca', 'bolero',
  'altpop', 'drill', 'grime', 'phonk', 'hyperpop', 'dreampop', 'shoegaze', 'pluggnb',
  'chillwave', 'darkwave', 'cloudrap', 'nightcore', 'vapor', 'baroque', 'opera', 'choral',
  'suite', 'aria', 'fugue', 'waltz', 'ballad', 'kpop', 'jpop', 'citypop',
  'taiko', 'tribal', 'chant', 'drone', 'world', 'newage', 'remix', 'cover',
  'mashup', 'edit', 'ferocious', 'venomous', 'clockwork', 'southpaw', 'bareknuckle', 'roundhouse',
  'yokozuna', 'luchador', 'grandmaster', 'desperado', 'psychobilly', 'industrial', 'relentless', 'nocturnal',
  'haymaker', 'armageddon', 'lightning', 'flamenco', 'chiptune', 'hairtrigger',
];

/** Verb-flavoured and motion words. 395 words. */
export const verbtrics: readonly string[] = [
  'buzz', 'click', 'code', 'crash', 'drop', 'flip', 'flow', 'hack',
  'jam', 'link', 'load', 'mint', 'mix', 'move', 'ping', 'post',
  'press', 'push', 'pull', 'render', 'roll', 'scan', 'send', 'share',
  'shine', 'slide', 'snap', 'spin', 'swipe', 'tap', 'text', 'tilt',
  'track', 'tune', 'type', 'update', 'upload', 'vibe', 'wave', 'zoom',
  'bounce', 'blast', 'boost', 'charge', 'crunch', 'dance', 'debug', 'deploy',
  'drip', 'edit', 'enter', 'escape', 'fetch', 'flash', 'fold', 'forge',
  'grab', 'join', 'jump', 'kick', 'launch', 'lift', 'login', 'logout',
  'mash', 'match', 'nudge', 'paste', 'print', 'reach', 'react', 'reboot',
  'refine', 'reset', 'revise', 'save', 'search', 'serve', 'spinup', 'start',
  'store', 'stream', 'swirl', 'trigger', 'tweet', 'unpack', 'unzip', 'vibrate',
  'warp', 'whirl', 'nano', 'micro', 'milli', 'centi', 'deci', 'deka',
  'hecto', 'kilo', 'tera', 'peta', 'exa', 'zetta', 'yotta', 'atto',
  'zepto', 'yocto', 'quant', 'quark', 'fractal', 'ratio', 'sigma', 'delta',
  'omega', 'theta', 'alpha', 'beta', 'lambda', 'phi', 'psi', 'tau',
  'pi', 'root', 'sum', 'prod', 'calc', 'count', 'scale', 'phase',
  'pulse', 'spark', 'drift', 'field', 'grid', 'axis', 'node', 'mesh',
  'bit', 'byte', 'pixel', 'tensor', 'vector', 'matrix', 'scalar', 'logic',
  'datum', 'array', 'stack', 'queue', 'chain', 'ring', 'cell', 'atom',
  'sync', 'chrono', 'tempo', 'tick', 'frame', 'cycle', 'loop', 'gluon',
  'neutron', 'ionium', 'vortex', 'dimension', 'singularity', 'gravic', 'spacor', 'frankie',
  'boingy', 'bouncy', 'wiggly', 'farty', 'sniffy', 'smiley', 'burpy', 'giggy',
  'drippy', 'snappy', 'zappy', 'blinky', 'glowy', 'flippy', 'fluffy', 'noisy',
  'quirky', 'wonky', 'jumpy', 'jiggy', 'puffy', 'swirly', 'twirly', 'cheeky',
  'goofy', 'loopy', 'spooky', 'slinky', 'clappy', 'dizzy', 'toasty', 'yummy',
  'tasty', 'snuggy', 'twitch', 'sneezy', 'peepy', 'drooly', 'grumpy', 'snorty',
  'itchy', 'scratch', 'sleepy', 'groovy', 'zany', 'etch', 'sketch', 'carve',
  'chisel', 'blend', 'shade', 'trace', 'glaze', 'spray', 'smudge', 'mold',
  'paint', 'draw', 'draft', 'weave', 'stitch', 'throw', 'cast', 'flare',
  'sculpt', 'splat', 'graff', 'stamp', 'stain', 'glue', 'cutout', 'layer',
  'montage', 'splice', 'blur', 'curve', 'chicky', 'icky', 'sassy', 'snarky',
  'zesty', 'glitzy', 'bossy', 'bratty', 'buzzy', 'flashy', 'baddy', 'boldy',
  'spicy', 'vixxy', 'jazzy', 'feisty', 'fizzy', 'saucy', 'perky', 'slyly',
  'flirty', 'witty', 'snippy', 'peppy', 'chill', 'boppy', 'vibey', 'breezy',
  'crisp', 'plucky', 'swanky', 'frisky', 'punchy', 'classy', 'tipsy', 'nutty',
  'zazzy', 'moxy', 'snazzy', 'blingy', 'wavy', 'tangy', 'risky', 'bubbly',
  'lilac', 'inky', 'scriby', 'dabby', 'smudgy', 'blendy', 'stainy', 'marky',
  'etchy', 'graffy', 'cutty', 'chalky', 'brusky', 'spongy', 'pasty', 'glazy',
  'dusty', 'sketchy', 'scrapy', 'patchy', 'clayey', 'grain', 'foggy', 'grainy',
  'blurry', 'spiky', 'gritty', 'crumby', 'sandy', 'painty', 'splash', 'swoosh',
  'doodle', 'stroke', 'dabble', 'weavy', 'mixxy', 'popsy', 'smear', 'dotty',
  'daft', 'barmy', 'dodgy', 'nifty', 'silly', 'clumsy', 'bonker', 'chippy',
  'muggy', 'poshy', 'rumpty', 'toffy', 'tickle', 'tizzy', 'bloopy', 'bugger',
  'chummy', 'blimey', 'whiffy', 'dimwit', 'tweedy', 'giddy', 'titchy', 'twitzy',
  'poppet', 'plonky', 'boffin', 'spiffy', 'twonky', 'gitty', 'wobbly', 'ruddy',
  'smirky', 'tubby', 'pesky', 'chortle', 'humbug', 'dart', 'yomp', 'zonk',
  'faff', 'dyne', 'lux', 'mach', 'kip', 'dozy', 'poky', 'spry',
  'daub', 'riff', 'mosh', 'zing', 'zizz', 'skedaddle', 'ricochet', 'lollygag',
  'smidgeon', 'squiggly', 'skittery', 'frabjous', 'kerfuffle', 'muon', 'gallivant', 'somersault',
  'bamboozle', 'metronome', 'flutterby',
];

/** Colours and cute-adjacent descriptors. 372 words. */
export const kawaiiolors: readonly string[] = [
  'aqua', 'beige', 'black', 'blue', 'blush', 'brown', 'coffee', 'crimson',
  'cyan', 'emerald', 'fuchsia', 'gray', 'green', 'jade', 'lime', 'magenta',
  'maroon', 'olive', 'orange', 'peach', 'pink', 'plum', 'purple', 'red',
  'rose', 'salmon', 'scarlet', 'tan', 'teal', 'tomato', 'violet', 'white',
  'yellow', 'almond', 'apples', 'apricot', 'ash', 'azure', 'berry', 'bistre',
  'brick', 'bronzy', 'canary', 'celery', 'cerule', 'cherry', 'citrine', 'claret',
  'dijon', 'flax', 'forest', 'garnet', 'glauc', 'hazel', 'indigo', 'khaki',
  'latte', 'lemon', 'linen', 'melon', 'mimosa', 'mint', 'mocha', 'moss',
  'mustard', 'navy', 'ochre', 'periwinkle', 'poppy', 'prune', 'raven', 'rouge',
  'ruby', 'rust', 'sage', 'sand', 'sepia', 'sienna', 'rusty', 'sky',
  'snow', 'taupe', 'topaz', 'umber', 'vermilion', 'boba', 'pocky', 'dango',
  'umami', 'ramen', 'matcha', 'tomo', 'momo', 'mikan', 'anko', 'taiyo',
  'neko', 'inu', 'usagi', 'kuma', 'tori', 'hato', 'sora', 'yuki',
  'hana', 'suzu', 'mizu', 'hikari', 'hoshi', 'smile', 'chibi', 'kawaii',
  'softe', 'cozy', 'dreamy', 'snuggy', 'puffy', 'spark', 'fluff', 'peachy',
  'milky', 'twink', 'plush', 'daisy', 'sunny', 'glowy', 'candy', 'rosie',
  'nya', 'piyo', 'mew', 'woof', 'squeak', 'poof', 'blink', 'honk',
  'bloop', 'tink', 'boing', 'poppi', 'plonk', 'nuzzle', 'huggy', 'sniff',
  'tickle', 'chirp', 'winky', 'meep', 'ribbon', 'cloudy', 'pastel', 'bubble',
  'sparkle', 'shiny', 'cupie', 'petal', 'pillow', 'creme', 'glaze', 'cotton',
  'snack', 'plume', 'dollie', 'frilly', 'bowie', 'snaily', 'tulip', 'muffin',
  'sakura', 'mirai', 'aiko', 'kiko', 'lulu', 'mika', 'nana', 'rin',
  'yumi', 'tama', 'fuwaf', 'yume', 'koko', 'suki', 'riko', 'emi',
  'ayame', 'musk', 'cedar', 'spice', 'soapy', 'rosin', 'smoky', 'woody',
  'earthy', 'freshy', 'lemony', 'bloomy', 'dusky', 'pepper', 'vanilla', 'floral',
  'meaty', 'briny', 'grassy', 'ocean', 'bready', 'yeasty', 'citrus', 'honeydew',
  'whirr', 'clang', 'ping', 'chime', 'clink', 'plop', 'ding', 'rustle',
  'swoosh', 'whisp', 'creak', 'rumble', 'drone', 'hum', 'thump', 'ticktock',
  'whoosh', 'sizzle', 'clack', 'pluck', 'murmur', 'giggle', 'purr', 'tinkle',
  'rough', 'softy', 'silky', 'velvet', 'grainy', 'sticky', 'slick', 'slimy',
  'gritty', 'warm', 'chill', 'numb', 'plushy', 'cool', 'greasy', 'dryish',
  'dewy', 'prickle', 'gooey', 'oily', 'tangly', 'clingy', 'crumb', 'crisp',
  'squish', 'tacky', 'aurum', 'azoth', 'elixir', 'essence', 'ether', 'focus',
  'homunculus', 'mandra', 'mercury', 'potion', 'prima', 'salem', 'sigil', 'spirit',
  'symbol', 'tinct', 'vessel', 'vitrum', 'amulet', 'ankh', 'charm', 'crown',
  'crystal', 'gemrod', 'grimoire', 'idol', 'relic', 'ring', 'rune', 'staff',
  'stone', 'talisman', 'torch', 'totem', 'wand', 'orb', 'seal', 'scroll',
  'tablet', 'amber', 'beryl', 'brimstone', 'dust', 'ichor', 'ink', 'lapis',
  'miasma', 'nectar', 'oil', 'powder', 'quartz', 'resin', 'salt', 'sap',
  'smoke', 'vapour', 'vine', 'wax', 'wine', 'arcana', 'augury', 'chaos',
  'circle', 'fate', 'flux', 'glyph', 'halo', 'omen', 'soul', 'veil',
  'vision', 'void', 'will', 'zeal', 'anvil', 'blade', 'bottle', 'chain',
  'forge', 'gear', 'hammer', 'lens', 'loom', 'pipe', 'press', 'vial',
  'wheel', 'yolk', 'oat', 'tuft', 'lace', 'boop', 'weft', 'kiln',
  'rasp', 'nib', 'niji', 'yuzu', 'sumi', 'kirakira', 'mochimochi', 'konpeito',
  'crucible', 'whetstone', 'lodestone', 'sprocket', 'fawn', 'lava', 'rime', 'chartreuse',
  'gunmetal', 'malachite', 'corduroy', 'gossamer',
];

/** Actions and states with meme energy. 518 words. */
export const memactions: readonly string[] = [
  'fusion', 'ignite', 'bond', 'crack', 'melt', 'boil', 'vapor', 'flare',
  'glow', 'burst', 'shock', 'phase', 'solid', 'liquid', 'plasma', 'freeze',
  'split', 'blend', 'react', 'chain', 'mix', 'flash', 'burn', 'shine',
  'steam', 'storm', 'swell', 'erupt', 'fling', 'ionize', 'merge', 'ripple',
  'charge', 'arc', 'rivet', 'sizzle', 'bubble', 'crash', 'crisp', 'foam',
  'rise', 'droplet', 'glint', 'soar', 'blink', 'jolt', 'quake', 'smelt',
  'grasp', 'absorb', 'adhere', 'decay', 'dilate', 'expand', 'excite', 'freezy',
  'mingle', 'morph', 'oxide', 'ozone', 'polar', 'quench', 'reflux', 'refine',
  'settle', 'shift', 'smoke', 'sublime', 'tumble', 'twist', 'whirl', 'weld',
  'zappy', 'melted', 'frozen', 'heated', 'cool', 'ionic', 'gamma', 'mega',
  'laser', 'sonic', 'atomic', 'plated', 'bonded', 'catalyst', 'boson', 'photon',
  'matrix', 'vector', 'scalar', 'tensor', 'nuclear', 'thermal', 'dynamic', 'kinetic',
  'elastic', 'spectra', 'nova', 'astro', 'stellar', 'orbital', 'lunar', 'solar',
  'blaze', 'frost', 'glacier', 'torrent', 'zephyr', 'gale', 'tempest', 'meme',
  'lol', 'rofl', 'lmao', 'bruh', 'yolo', 'fail', 'win', 'omg',
  'wtf', 'noob', 'pwned', 'owned', 'rekt', 'sus', 'simp', 'cringe',
  'derp', 'troll', 'grump', 'doge', 'pepe', 'nyan', 'cheems', 'shibe',
  'pog', 'kappa', 'vibe', 'epic', 'yeet', 'dab', 'smh', 'rip',
  'okboom', 'thug', 'boi', 'karen', 'zoomr', 'stan', 'flex', 'lit',
  'cap', 'fax', 'drip', 'slay', 'rizz', 'vibechk', 'catjam', 'stonks',
  'doomer', 'wojak', 'gigach', 'sigma', 'chonk', 'bless', 'sneed', 'skibidi',
  'mood', 'cope', 'edgy', 'npc', 'rage', 'peepo', 'bongo', 'bonk',
  'gyatt', 'bet', 'mid', 'fire', 'susmax', 'aura', 'goofy', 'basedg',
  'slaps', 'goated', 'drippy', 'vibing', 'yapper', 'skibi', 'bro', 'fr',
  'onnah', 'brisky', 'oomf', 'mainch', 'fanum', 'pluh', 'gyalz', 'skrrt',
  'oomfie', 'snacc', 'delulu', 'hodl', 'wagmi', 'fomo', 'degen', 'ape',
  'moon', 'pump', 'dump', 'stonk', 'giga', 'mev', 'btc', 'dust',
  'nonce', 'crypto', 'wave', 'doom', 'alt', 'normie', 'feral', 'chaos',
  'weird', 'based', 'glitch', 'alpha', 'omega', 'esthet', 'irony', 'console',
  'arcade', 'button', 'screen', 'cursor', 'server', 'router', 'stream', 'weapon',
  'shield', 'engine', 'module', 'avatar', 'helmet', 'sensor', 'socket', 'device',
  'driver', 'buffer', 'packet', 'script', 'switch', 'mouse', 'mobile', 'rig',
  'action', 'racing', 'puzzle', 'horror', 'stealth', 'combat', 'shooter', 'sim',
  'builder', 'clicker', 'sandbox', 'rhythm', 'retro', 'mmo', 'moba', 'idle',
  'core', 'sniper', 'healer', 'tanker', 'mage', 'rogue', 'scout', 'hunter',
  'ranger', 'cleric', 'bard', 'monk', 'druid', 'runner', 'pilot', 'hacker',
  'miner', 'leader', 'camper', 'raider', 'scorer', 'gg', 'glhf', 'ezwin',
  'lagger', 'clutch', 'combo', 'boost', 'smurf', 'carry', 'feed', 'farm',
  'tilted', 'spawn', 'loot', 'drop', 'queue', 'party', 'squad', 'guild',
  'clan', 'match', 'round', 'score', 'level', 'token', 'key', 'map',
  'chest', 'crate', 'potion', 'orb', 'gem', 'coin', 'credit', 'power',
  'skill', 'perk', 'bonus', 'rank', 'badge', 'medal', 'point', 'stars',
  'meter', 'energy', 'drone', 'blade', 'castle', 'portal', 'planet', 'sector',
  'realm', 'temple', 'arena', 'zone', 'field', 'forest', 'ocean', 'canyon',
  'valley', 'citadel', 'station', 'colony', 'base', 'tower', 'village', 'hub',
  'battle', 'camp', 'island', 'space', 'vault', 'fort', 'reload', 'target',
  'aimbot', 'macro', 'update', 'patch', 'build', 'draft', 'timing', 'cancel',
  'parry', 'dodge', 'attack', 'defend', 'heal', 'focus', 'revive', 'assist',
  'escape', 'guard', 'shoot', 'block', 'roll', 'jump', 'gamer', 'pro',
  'elite', 'harder', 'toxic', 'speedy', 'flashy', 'crafty', 'sweaty', 'steamy',
  'chill', 'brisk', 'clean', 'sharp', 'car', 'truck', 'jeep', 'wagon',
  'sedan', 'coupe', 'van', 'taxi', 'bus', 'lorry', 'cycle', 'bike',
  'scooter', 'buggy', 'tractor', 'train', 'metro', 'tram', 'trolley', 'rover',
  'skate', 'board', 'sled', 'chariot', 'caravan', 'coach', 'moto', 'dirt',
  'racer', 'drift', 'kart', 'sprint', 'cruise', 'sledge', 'draggy', 'gokart',
  'buggie', 'trike', 'sports', 'jumper', 'pickup', 'plane', 'jet', 'glider',
  'craft', 'shuttle', 'rocket', 'ufo', 'orbiter', 'dirigible', 'falcon', 'soarer',
  'winger', 'flappy', 'helium', 'skycar', 'lander', 'blimp', 'flier', 'flybot',
  'hopper', 'skyjet', 'pod', 'boat', 'ship', 'canoe', 'yacht', 'raft',
  'sloop', 'skiff', 'dinghy', 'tug', 'barge', 'ferry', 'sailor', 'sub',
  'submarine', 'hover', 'kayak', 'trawler', 'speeder', 'crawler', 'cruiser', 'hoverb',
  'swoopr', 'mecha', 'walker', 'winged', 'floater', 'telepod', 'warpjet', 'timecar',
  'drifter', 'tank', 'cart', 'shipper', 'flycar', 'wormax', 'airbus', 'skybus',
  'finalboss', 'monorail', 'streamliner', 'hydrofoil', 'cosmodrome', 'scramjet', 'antigrav', 'cyclotron',
  'positronic', 'brainrot', 'speedrun', 'ragequit', 'sidequest', 'cheatcode',
];

/** Places, terrain and habitats. 340 words. */
export const biome: readonly string[] = [
  'alpaca', 'ant', 'antlion', 'asp', 'baboon', 'badger', 'bass', 'bat',
  'bear', 'beaver', 'bee', 'beetle', 'bird', 'bison', 'boa', 'boar',
  'bobcat', 'booby', 'bovid', 'bug', 'camel', 'canid', 'carp', 'cat',
  'cod', 'cougar', 'cow', 'crab', 'crane', 'crayfish', 'cricket', 'crow',
  'cuckoo', 'deer', 'dingo', 'dog', 'donkey', 'dove', 'duck', 'eagle',
  'eel', 'egret', 'elk', 'emu', 'falcon', 'ferret', 'finch', 'fish',
  'flea', 'fly', 'fowl', 'fox', 'frog', 'gecko', 'gerbil', 'gibbon',
  'goat', 'goose', 'gopher', 'grouse', 'gull', 'guppy', 'hare', 'hawk',
  'heron', 'hornet', 'horse', 'hyena', 'iguana', 'impala', 'jackal', 'jaguar',
  'jay', 'kiwi', 'koala', 'koi', 'krill', 'ladybug', 'lark', 'leech',
  'lemur', 'lion', 'lizard', 'llama', 'lobster', 'locust', 'loon', 'louse',
  'lynx', 'macaw', 'magpie', 'mammal', 'manatee', 'marlin', 'marmot', 'marten',
  'meerkat', 'mink', 'minnow', 'mite', 'mole', 'monkey', 'moose', 'moth',
  'mouse', 'mule', 'newt', 'ocelot', 'octopus', 'opossum', 'orca', 'ostrich',
  'otter', 'owl', 'ox', 'panda', 'panther', 'parrot', 'peafowl', 'pelican',
  'penguin', 'perch', 'pig', 'pigeon', 'pike', 'prawn', 'primate', 'puffin',
  'puma', 'python', 'quail', 'quelea', 'quokka', 'rabbit', 'raccoon', 'rat',
  'reptile', 'rodent', 'rook', 'rooster', 'salmon', 'sawfish', 'scallop', 'shark',
  'sheep', 'shrew', 'shrimp', 'skink', 'skunk', 'sloth', 'slug', 'snail',
  'snake', 'snipe', 'sole', 'spider', 'squid', 'swan', 'swift', 'takin',
  'tapir', 'tarsier', 'tern', 'thrush', 'tick', 'tiger', 'tiglon', 'toad',
  'toucan', 'trout', 'tuna', 'turkey', 'turtle', 'urial', 'viper', 'vole',
  'vulture', 'walrus', 'wasp', 'weasel', 'whale', 'wolf', 'wombat', 'worm',
  'wren', 'yak', 'zebra', 'rex', 'trex', 'raptor', 'triceratops', 'stegosaurus',
  'ankylosaurus', 'spinosaurus', 'brontosaurus', 'allosaurus', 'iguanodon', 'compy', 'paras', 'troodon',
  'velociraptor', 'titan', 'dino', 'quetzal', 'plesiosaur', 'mosasaurus', 'carnotaurus', 'gorgosaurus',
  'ceratosaurus', 'edmontosaurus', 'hadrosaurus', 'apple', 'apricot', 'avocado', 'banana', 'berry',
  'bilberry', 'blackberry', 'cantaloupe', 'cherry', 'citron', 'coconut', 'currant', 'date',
  'fig', 'guava', 'grape', 'lemon', 'lime', 'lychee', 'mango', 'melon',
  'orange', 'papaya', 'peach', 'pear', 'prune', 'raisin', 'tamarind', 'tomato',
  'amaranth', 'bamboo', 'beet', 'cabbage', 'carrot', 'celery', 'chard', 'chilli',
  'chives', 'corn', 'cress', 'daikon', 'edamame', 'endive', 'garlic', 'ginger',
  'leek', 'lettuce', 'lotus', 'mushroom', 'okra', 'onion', 'parsnip', 'pea',
  'peanut', 'pepper', 'potato', 'radish', 'spinach', 'sprout', 'squash', 'turnip',
  'yam', 'pixie', 'jack', 'nessie', 'porcupine', 'armadillo', 'capybara', 'pangolin',
  'platypus', 'chinchilla', 'wildebeest', 'hippopotamus', 'cassowary', 'kookaburra', 'albatross', 'flamingo',
  'hummingbird', 'chameleon', 'mudpuppy', 'barracuda', 'cuttlefish', 'wobbegong', 'mudskipper', 'porpoise',
  'dragonfly', 'bumblebee', 'tarantula', 'trilobite', 'smilodon', 'megalodon', 'pterodactyl', 'titanoboa',
  'artichoke', 'kohlrabi', 'rutabaga', 'persimmon', 'cloudberry', 'chanterelle', 'jackalope', 'numbat',
  'fennec', 'narwhal', 'okapi', 'dugong', 'piranha', 'lamprey', 'cicada', 'mantis',
  'earwig', 'weevil', 'katydid', 'axolotl', 'caiman', 'tuatara', 'mammoth', 'quince',
  'pomelo', 'loquat', 'durian', 'jicama', 'chayote', 'nopal', 'porcini', 'foxglove',
  'quoll', 'jerboa', 'potoo', 'motmot',
];

/** Creatures, materials and things. 311 words. */
export const monsterials: readonly string[] = [
  'stone', 'clay', 'flint', 'marble', 'basalt', 'granite', 'slate', 'obsidian',
  'quartz', 'onyx', 'opal', 'agate', 'pearl', 'ivory', 'glass', 'bronze',
  'copper', 'silver', 'gold', 'iron', 'steel', 'brass', 'tin', 'lead',
  'zinc', 'nickel', 'chrome', 'ionium', 'radon', 'argon', 'neon', 'xenon',
  'lithic', 'aurite', 'baryon', 'bosium', 'tachyn', 'carbon', 'silica', 'graphene',
  'helium', 'nitron', 'sodium', 'oxium', 'hydron', 'tungsten', 'uranic', 'plutonium',
  'cobalt', 'iridium', 'osmium', 'vanadium', 'zircon', 'chromium', 'yttrium', 'tellurium',
  'selenium', 'radium', 'meteor', 'comet', 'asteroid', 'nebula', 'celestial', 'galactic',
  'void', 'plasm', 'crater', 'dust', 'lumen', 'spectral', 'wormhole', 'quantum',
  'fluxor', 'pulsar', 'spinel', 'aurora', 'glacial', 'cryox', 'glimr', 'alien',
  'xenite', 'astrid', 'vibran', 'neural', 'drakon', 'novaic', 'lumite', 'gaium',
  'silven', 'orion', 'eclipse', 'velium', 'lunite', 'solite', 'arcan', 'cryton',
  'nebrix', 'ethyra', 'quantx', 'celium', 'voidal', 'choco', 'fudge', 'caramel',
  'toffee', 'taffy', 'nougat', 'marzipan', 'truffle', 'bonbon', 'jelly', 'gummy',
  'lolly', 'sugar', 'minty', 'cookie', 'donut', 'wafer', 'cream', 'mocha',
  'honey', 'dragon', 'wyrm', 'drake', 'hydra', 'basilisk', 'wyvern', 'naga',
  'serpent', 'leviathan', 'tannin', 'midgar', 'behemoth', 'tarasque', 'daemon', 'demon',
  'djinn', 'oni', 'rakshasa', 'asura', 'ifrit', 'succub', 'incubus', 'ghoul',
  'banshee', 'shade', 'specter', 'phantom', 'wraith', 'poltergeist', 'maca', 'zombie',
  'mummy', 'vampyr', 'vampire', 'lich', 'skeleton', 'ghost', 'revenant', 'compa',
  'werewolf', 'centaur', 'satyr', 'faun', 'harpy', 'sirene', 'mermaid', 'selkie',
  'minotaur', 'chimera', 'griffin', 'hippogriff', 'sphinx', 'pegasus', 'lamia', 'gorgon',
  'medusa', 'morty', 'giant', 'ogre', 'cyclops', 'yeti', 'troll', 'golem',
  'kraken', 'jotunn', 'ettin', 'angel', 'seraph', 'cherub', 'nephilim', 'valkyr',
  'nymph', 'dryad', 'muse', 'oracle', 'phoenix', 'kirin', 'unicorn', 'pegasi',
  'nahual', 'chaneq', 'alux', 'teotl', 'ahuizotl', 'tzitzimitl', 'xolotl', 'quetzalcoatl',
  'kukulkan', 'camazotz', 'coyotl', 'tlaloc', 'balam', 'itzamna', 'cholo', 'wendigo',
  'skinwalker', 'sasquatch', 'baba', 'kelpie', 'draugr', 'bogart', 'gremlin', 'krampus',
  'pooka', 'redcap', 'kobold', 'imp', 'spriggan', 'hobgoblin', 'brownie', 'gnome',
  'elf', 'orc', 'tengu', 'kitsune', 'yokai', 'bakeneko', 'oniwaban', 'tanuki',
  'nuckelavee', 'promethium', 'electrum', 'cinnabar', 'xenolith', 'magnetar', 'neutronium', 'phlogiston',
  'ectoplasm', 'umbralite', 'keraunite', 'jawbreaker', 'gashadokuro', 'rokurokubi', 'jorogumo', 'kamaitachi',
  'tsukumogami', 'shinigami', 'tsuchinoko', 'jiangshi', 'dokkaebi', 'bulgasari', 'tikbalang', 'bakunawa',
  'manticore', 'karkadann', 'lamashtu', 'cipactli', 'curupira', 'mapinguari', 'mishipeshu', 'qalupalik',
  'pyrite', 'bismuth', 'rhodium', 'niobium', 'kyanite', 'tektite', 'quasar', 'geode',
  'nullite', 'orochi', 'raiju', 'kodama', 'yurei', 'cadejo', 'amaru', 'xtabay',
  'vetala', 'rangda', 'ammit', 'rusalka', 'strigoi', 'tupilaq', 'bunyip', 'verdigris',
  'alkahest', 'butterscotch', 'marshmallow', 'gandharva', 'doppelganger', 'wolpertinger', 'amphisbaena', 'galena',
  'peridot', 'gallium', 'lechuza', 'garuda', 'makara', 'marid', 'anansi',
];

/** Every pool, in canonical order. */
export const POOLS = {
  ninjactives, verbtrics, kawaiiolors, memactions, biome, monsterials,
} as const;

export type PoolName = keyof typeof POOLS;

/** Canonical pool order — stable, so generated output is reproducible. */
export const POOL_NAMES: readonly PoolName[] = [
  'ninjactives', 'verbtrics', 'kawaiiolors', 'memactions', 'biome', 'monsterials',
];
